# Generated by Django 5.0.1 on 2024-02-04 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='upload',
        ),
    ]
