# Generated by Django 5.0.1 on 2024-02-08 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_file_deleted_alter_file_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='user',
            new_name='username',
        ),
    ]
